"""Script.mako
Mako template for generating migration files."""

# migration meta information
revision = '85a4ce77590b'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise_library', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercise_library', 'muscle_group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_exercise_library_name'), table_name='exercise_library')
    op.create_index(op.f('ix_exercise_library_name'), 'exercise_library', ['name'], unique=True)
    op.alter_column('exercises', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('food_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('food_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('food_items', 'serving_size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('food_items', 'calories',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('food_items', 'protein_g',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('food_items', 'carbs_g',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('food_items', 'fat_g',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('food_items', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('nutrition_entries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('nutrition_entries', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('nutrition_entries', 'meal_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('nutrition_entries', 'meal_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('nutrition_entries', 'calories',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('nutrition_entries', 'protein_g',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('nutrition_entries', 'carbs_g',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('nutrition_entries', 'fat_g',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('nutrition_entries', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('sets', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sets', 'reps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sets', 'weight',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('sets', 'set_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_settings', 'weight_unit',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'kg'"))
    op.alter_column('user_settings', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_settings', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('workouts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workouts', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('workouts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_settings', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_settings', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('user_settings', 'weight_unit',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'kg'"))
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sets', 'set_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('sets', 'weight',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('sets', 'reps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sets', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('nutrition_entries', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('nutrition_entries', 'fat_g',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('nutrition_entries', 'carbs_g',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('nutrition_entries', 'protein_g',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('nutrition_entries', 'calories',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('nutrition_entries', 'meal_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('nutrition_entries', 'meal_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('nutrition_entries', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('nutrition_entries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('food_items', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('food_items', 'fat_g',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('food_items', 'carbs_g',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('food_items', 'protein_g',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('food_items', 'calories',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('food_items', 'serving_size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('food_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('food_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercises', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_exercise_library_name'), table_name='exercise_library')
    op.create_index(op.f('ix_exercise_library_name'), 'exercise_library', ['name'], unique=False)
    op.alter_column('exercise_library', 'muscle_group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercise_library', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
